# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4.2.1

    - name: Set up Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version: '1.20'

    - name: Run go mod tidy
      run: |
        set -e
        go mod tidy
        output=$(git status -s)
        if [ -z "${output}" ]; then
         exit 0
        fi
        echo 'We wish to maintain a tidy state for go mod. Please run `go mod tidy` on your branch, commit and push again.'
        echo 'Running `go mod tidy` on this CI test yields with the following changes:'
        echo "$output"
        exit 1

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.1.1
            
    - name: Build
      run: go build ./...
